name: sprotbuzz
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  #internet connection 
  internet_connection_checker: ^1.0.0+1
  #text conver to html 
  html: ^0.15.4
  # analytics

  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  http: ^1.1.2
  animated_bottom_navigation_bar: ^1.3.0
  carousel_slider: ^4.2.1
  firebase_analytics: ^10.7.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_local_notifications: ^16.3.0
  intl: ^0.18.1
  connectivity: ^3.0.6
  dotted_border: ^2.1.0
  #ads component
  google_mobile_ads: ^4.0.0
  facebook_audience_network: ^1.0.1
  share_plus: ^7.2.1
  shimmer: ^3.0.0
  readmore: ^2.2.0
  video_player: ^2.8.2
  timezone: ^0.9.2
  collection: ^1.18.0
  flutter_tts: ^3.8.5
  url_launcher: ^6.2.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/home_menu_icon/
    - assets/icons/
    - assets/animation/
    - assets/
    - assets/language/
    - 
    - assets/user/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf