name: mycricketline
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.0+2

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  readmore: ^2.1.0

  floating: ^2.0.1
  carousel_slider: ^4.0.0
  provider: ^6.0.5
  flutter_widget_from_html: ^0.10.2
  flutter_tts: ^3.7.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  riverpod: ^2.3.6
  lottie: ^2.5.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  html: ^0.15.4
  localstorage: ^4.0.1+4
  google_mobile_ads: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  

  assets:
    - images/live.gif
    - images/six.gif
    - images/four.gif
    - images/vs.png
    - images/boll.gif
    - images/logo.gif
    - images/vs1.png
    - images/vs2.png
    - images/tv.png
    - images/toss.png
    - images/over.gif
    - images/Line1.png
    - images/dot.png
    - images/home.png
    - images/short.png
    - images/match.png
    - images/textlogo.png
    - images/dark_mode.png
    - images/light_mode.png
    - images/empty.json
    - assets/