// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTt1_CHnYLz5gi3UGkfJtymWf2wqB0AqU',
    appId: '1:381985912305:web:79e85ada7ee8af8ed20050',
    messagingSenderId: '381985912305',
    projectId: 'sprotbuzz',
    authDomain: 'sprotbuzz.firebaseapp.com',
    storageBucket: 'sprotbuzz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALlHLbvKFrdX0yAJEYjLIJLEtjnmD8dSo',
    appId: '1:381985912305:android:eecb3f8171df6cefd20050',
    messagingSenderId: '381985912305',
    projectId: 'sprotbuzz',
    storageBucket: 'sprotbuzz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRAlQLmMjmhlMjfxq2dSKQhANBsauxUM',
    appId: '1:381985912305:ios:6be2bfe8e1dd134fd20050',
    messagingSenderId: '381985912305',
    projectId: 'sprotbuzz',
    storageBucket: 'sprotbuzz.appspot.com',
    iosBundleId: 'com.example.sprotbuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKRAlQLmMjmhlMjfxq2dSKQhANBsauxUM',
    appId: '1:381985912305:ios:9789dcdf069f700bd20050',
    messagingSenderId: '381985912305',
    projectId: 'sprotbuzz',
    storageBucket: 'sprotbuzz.appspot.com',
    iosBundleId: 'com.example.sprotbuzz.RunnerTests',
  );
}
